ARG RUBY_VERSION=3.3.6
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base
ENV RAILS_ENV=development
# Rails app lives here
WORKDIR /rails
# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl build-essential libpq-dev libjemalloc2 libvips postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle lock --add-platform ruby
RUN bundle lock --add-platform x86_64-linux
RUN gem install mini_portile2 -v 2.8.0
RUN bundle install -j $(nproc)
# Copy application code
COPY . .
